### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by DazWilkin** [Soluto/golang-docker-healthcheck#1]
Used your repo as an examplar after finding it today:
https://medium.com/google-cloud/dockerfile-go-healthchecks-k8s-9a87d5c5b4cb

Thanks for creating it!

**Comment by ebickle** [comment]
Glad it was a help! We're archiving the repository but keeping it online in case it's helpful for others. As part of that we're closing the open issues and pull requests. Good luck with your projects!
